### ISSUE TITLE
Get it uploaded!

### ISSUE THREAD

**Issue by bill-c-martin** [stretchnate/budget_app#1]
@stretchnate After hearing about this app for years now, I'm looking forward to seeing it finally :smile:

**Comment by stretchnate** [comment]
@bill-c-martin the funny thing is, I think if you were to look at it line by line you'd probably be able to tell the code I wrote when I first started from the newer stuff. Kind of like hieroglyphics in a time warp :).

**Comment by stretchnate** [comment]
@bill-c-martin btw, I actually uploaded it to a new repo called codeigniter_apps because there are more apps in the repo than just the budget app. Sorry for the confusion.

**Comment by bill-c-martin** [comment]
@stretchnate I'll have to check it out sometime. Going on hieroglyphic time warps into my coding past consistently repulses me every time!

**Comment by bill-c-martin** [comment]
@stretchnate By the way, why don't you separate this app out into it's own repo, separate from your other code igniter apps? That way you can track issues for it separately, have it's own readme, contribution instructions, etc. Speaking of which, do you have any known issues/enhancements for it? I'd be glad to lend a hand sometime. I've been wanting to get CodeIgniter under my belt for years now.

**Comment by stretchnate** [comment]
@bill-c-martin The apps are all together because I didn't want to have duplicates of the core CI libraries and because I was the only one working on any of them when I originally created the git repo. However, the only app that still has a heartbeat is the budget app, I am actually going to remove the evencolumn app altogether since it is no longer something I'm involved in.
As far as what needs to be done... that's a fairly lengthy list. I'd really like to re-factor the whole thing, I started doing that a while back but I'm streaky at best when it comes to working on it. It would also be nice to upgrade it to a newer version of CI (and thus a newer version of PHP). The DB tables need to be re-factored as well, I'm not sure what I was thinking when I created the tables but they've always driven me nuts (naming conventions right?).
The bad part for me right now is one of my PC's died and I had to move the app to what used to be my development machine just so the one other person on the planet who uses this app could do her budget (yes it's my mom, don't judge me ;) ).
If you are seriously down for tackling this I'll put together a list of priorities and include it in the repo. maybe I'll see if I can put the live site out on a heroku dyno or something so it's not being disturbed while everything else is being done.

**Comment by bill-c-martin** [comment]
@stretchnate Sounds like all sorts of fun. I'm pretty streaky too. I spend most of my off-work coding trying to learn something (learning a new language, design pattern, etc), rather than working on a product that's worth a damn. So this would be a welcome change of pace.

If you isolated the app to its own repo, you'd be able to use the issue tracker for it. Besides, it'd be easier to reference on a resume. If you star it yourself, it'll show as your top repo on your profile.

How settled are you on sticking with CI? Larvel seems to have [ascended to kingship](http://learninglaravel.net/most-popular-php-frameworks-2015-infographic) the [last few years](https://www.google.com/trends/explore#q=%2Fm%2F0jwy148%2C%20%2Fm%2F02qgdkj%2C%20%2Fm%2F09cjcl%2C%20%2Fm%2F09t3sp%2C%20phalcon&date=1%2F2010%2076m&cmpt=q&tz=Etc%2FGMT%2B4)..

And yeah, Heroku would be pretty cool. 

And since you want to rewrite the database, that'd mean model rewriting, so that'd be a good time to write massive amounts of unit tests :+1: 

And also +1 for us for having a casual discussion of great breadth in an issue tracker on github lol

**Comment by stretchnate** [comment]
@bill-c-martin I actually wouldn't mind migrating to Laravel, and since the majority of the code needs to be refactored anyway that would be a good time to do it.

Now you've got me thinking we could also possibly integrate travis-ci for continuous integration... maybe by the time we're done we'll actually have something.

**Comment by bill-c-martin** [comment]
@stretchnate I've been seeing projects here on github with that "build passing" image on them for a while now, and have been interested in Travis CI ever since.
